### ISSUE TITLE
Crash shortly after world load

### ISSUE THREAD

**Issue by Bluerobin427** [DrasticDemise/Simply-Magic-2#14]
I was excited to get this going on Curse, so I downloaded, genned a world, and started looking around. I walked a couple blocks, looked at a plant that was floating above a halfslab of BuildingBricks grass, and crashed. This was all within about 30 seconds of starting up, so I'm not 100% sure that anything I did caused the crash, but I included the crash log below. I tried turning off BuildingBricks in the Curse launcher and new worlds don't gen, so I'm guessing there's some config stuff going on there that I don't have time to figure out tonight. Sorry. Anyway, here's my crash log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/12/16 7:34 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoublePlant$EnumBlockHalf, values=[upper, lower]} as it does not exist in BlockState{block=buildingbrickscompatvanilla:grass_slab, properties=[half, snowy]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at net.minecraft.block.BlockDoublePlant.func_176201_c(BlockDoublePlant.java:277)
    at mcp.mobius.waila.addons.vanillamc.HUDHandlerVanilla.getWailaStack(HUDHandlerVanilla.java:79)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:155)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:98)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:67)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:78)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_262_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at net.minecraft.block.BlockDoublePlant.func_176201_c(BlockDoublePlant.java:277)
    at mcp.mobius.waila.addons.vanillamc.HUDHandlerVanilla.getWailaStack(HUDHandlerVanilla.java:79)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:155)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:98)
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:67)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:78)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_262_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Bluerobin427'/386, l='MpServer', x=230.93, y=64.00, z=-161.92]]
    Chunk stats: MultiplayerChunkCache: 583, 583
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 256.00,64.00,-156.00 - World: (256,64,-156), Chunk: (at 0,4,4 in 16,-10; contains blocks 256,0,-160 to 271,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 584 game time, 584 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 147 total; [EntityBat['Bat'/6212, l='MpServer', x=292.00, y=28.04, z=-87.52], EntityBat['Bat'/6214, l='MpServer', x=291.38, y=27.77, z=-87.77], EntityBat['Bat'/6215, l='MpServer', x=288.48, y=26.39, z=-90.76], EntityBat['Bat'/6216, l='MpServer', x=291.00, y=26.72, z=-87.25], EntityAuraNode['Aura Node'/83, l='MpServer', x=102.50, y=12.50, z=-209.50], EntityAuraNode['Aura Node'/84, l='MpServer', x=122.50, y=74.50, z=-301.50], EntityAuraNode['Aura Node'/85, l='MpServer', x=119.50, y=91.50, z=-268.50], EntityAuraNode['Aura Node'/107, l='MpServer', x=152.50, y=63.50, z=-184.50], EntitySheep['Sheep'/111, l='MpServer', x=174.19, y=70.00, z=-234.63], EntitySheep['Sheep'/112, l='MpServer', x=175.84, y=69.50, z=-235.47], EntitySkeleton['Skeleton'/2160, l='MpServer', x=187.50, y=22.00, z=-217.50], EntitySheep['Sheep'/113, l='MpServer', x=172.44, y=70.50, z=-233.50], EntitySkeleton['Skeleton'/2161, l='MpServer', x=186.50, y=22.00, z=-217.50], EntitySheep['Sheep'/114, l='MpServer', x=175.47, y=70.00, z=-237.00], EntitySkeleton['Skeleton'/2162, l='MpServer', x=186.50, y=22.00, z=-216.50], EntitySheep['Sheep'/116, l='MpServer', x=180.03, y=63.47, z=-183.13], EntitySheep['Sheep'/117, l='MpServer', x=169.97, y=63.00, z=-188.00], EntitySheep['Sheep'/118, l='MpServer', x=176.50, y=63.00, z=-181.88], EntitySheep['Sheep'/119, l='MpServer', x=174.38, y=63.00, z=-182.41], EntityPig['Pig'/120, l='MpServer', x=186.97, y=64.00, z=-97.94], EntityPig['Pig'/121, l='MpServer', x=182.28, y=64.50, z=-104.13], EntityPig['Pig'/122, l='MpServer', x=182.50, y=66.00, z=-106.50], EntityPig['Pig'/123, l='MpServer', x=183.50, y=64.00, z=-104.50], EntitySheep['Sheep'/124, l='MpServer', x=193.53, y=67.00, z=-241.66], EntityCow['Cow'/128, l='MpServer', x=199.50, y=68.00, z=-187.50], EntityCow['Cow'/129, l='MpServer', x=198.09, y=70.00, z=-194.81], EntityCow['Cow'/130, l='MpServer', x=193.50, y=64.00, z=-192.50], EntityCreeper['Creeper'/2178, l='MpServer', x=198.81, y=24.00, z=-173.53], EntityCow['Cow'/131, l='MpServer', x=193.50, y=65.00, z=-195.50], EntityCreeper['Creeper'/2179, l='MpServer', x=177.34, y=11.00, z=-161.00], EntityItem['item.tile.mushroom'/140, l='MpServer', x=193.75, y=20.00, z=-211.09], EntityCow['Cow'/141, l='MpServer', x=201.19, y=70.00, z=-194.50], EntityCow['Cow'/142, l='MpServer', x=202.44, y=70.00, z=-194.50], EntityCow['Cow'/143, l='MpServer', x=203.97, y=70.00, z=-194.50], EntityCow['Cow'/144, l='MpServer', x=205.50, y=70.00, z=-197.50], EntityAuraNode['Aura Node'/145, l='MpServer', x=204.50, y=71.50, z=-203.50], EntityItem['item.tile.mushroom11'/146, l='MpServer', x=207.19, y=11.00, z=-179.22], EntityAuraNode['Aura Node'/163, l='MpServer', x=235.50, y=63.50, z=-267.50], EntityCow['Cow'/164, l='MpServer', x=237.43, y=71.00, z=-194.27], EntityCow['Cow'/165, l='MpServer', x=247.72, y=70.00, z=-196.69], EntityCow['Cow'/166, l='MpServer', x=241.97, y=71.00, z=-196.91], EntityCow['Cow'/167, l='MpServer', x=245.22, y=70.00, z=-201.84], EntitySheep['Sheep'/168, l='MpServer', x=244.55, y=62.15, z=-156.79], EntitySheep['Sheep'/169, l='MpServer', x=254.81, y=66.00, z=-165.97], EntitySheep['Sheep'/170, l='MpServer', x=243.42, y=64.00, z=-163.52], EntitySheep['Sheep'/171, l='MpServer', x=242.38, y=65.00, z=-168.91], EntityPig['Pig'/173, l='MpServer', x=244.81, y=69.00, z=-82.22], EntityAuraNode['Aura Node'/180, l='MpServer', x=248.50, y=77.50, z=-258.50], EntityCow['Cow'/181, l='MpServer', x=252.50, y=67.00, z=-237.50], EntityCow['Cow'/183, l='MpServer', x=250.81, y=67.50, z=-240.03], EntityCow['Cow'/184, l='MpServer', x=249.28, y=67.00, z=-240.78], EntityCow['Cow'/185, l='MpServer', x=252.81, y=70.00, z=-191.75], EntityCow['Cow'/186, l='MpServer', x=245.13, y=71.00, z=-189.84], EntityCow['Cow'/187, l='MpServer', x=259.84, y=69.47, z=-202.16], EntityCow['Cow'/188, l='MpServer', x=262.91, y=70.00, z=-193.03], EntityHorse['Horse'/189, l='MpServer', x=253.53, y=70.00, z=-185.47], EntityHorse['Horse'/190, l='MpServer', x=252.00, y=70.00, z=-187.00], EntityHorse['Horse'/191, l='MpServer', x=251.09, y=71.00, z=-178.72], EntityItem['item.tile.mushroom0'/192, l='MpServer', x=254.88, y=14.00, z=-148.13], EntityPig['Pig'/193, l='MpServer', x=257.50, y=71.00, z=-115.50], EntityPig['Pig'/194, l='MpServer', x=255.50, y=71.00, z=-116.50], EntityPig['Pig'/195, l='MpServer', x=257.28, y=71.00, z=-118.22], EntityPig['Pig'/196, l='MpServer', x=254.09, y=71.00, z=-118.69], EntityRabbit['Rabbit'/197, l='MpServer', x=253.50, y=70.00, z=-104.50], EntityRabbit['Rabbit'/198, l='MpServer', x=253.34, y=70.00, z=-105.66], EntityRabbit['Rabbit'/199, l='MpServer', x=251.34, y=70.00, z=-105.66], EntityAuraNode['Aura Node'/200, l='MpServer', x=258.50, y=70.50, z=-192.50], EntityCow['Cow'/201, l='MpServer', x=280.06, y=65.50, z=-140.50], EntityCow['Cow'/202, l='MpServer', x=278.16, y=66.50, z=-141.84], EntityCow['Cow'/203, l='MpServer', x=278.16, y=64.50, z=-139.19], EntityCow['Cow'/204, l='MpServer', x=277.50, y=63.00, z=-136.50], EntityCow['Cow'/217, l='MpServer', x=303.50, y=66.00, z=-143.50], EntityCow['Cow'/218, l='MpServer', x=304.50, y=64.00, z=-140.50], EntityCow['Cow'/219, l='MpServer', x=306.50, y=65.00, z=-141.50], EntityCow['Cow'/220, l='MpServer', x=306.50, y=64.00, z=-138.50], EntityAuraNode['Aura Node'/233, l='MpServer', x=308.50, y=71.50, z=-157.50], EntityPlayerSP['Bluerobin427'/386, l='MpServer', x=230.93, y=64.00, z=-161.92], EntityBat['Bat'/433, l='MpServer', x=192.00, y=33.56, z=-174.50], EntityBat['Bat'/448, l='MpServer', x=215.84, y=49.47, z=-176.47], EntitySquid['Squid'/452, l='MpServer', x=193.78, y=56.91, z=-218.41], EntityItem['item.tile.gravel'/2546, l='MpServer', x=218.63, y=23.00, z=-146.06], EntitySquid['Squid'/563, l='MpServer', x=177.25, y=60.97, z=-157.53], EntitySquid['Squid'/564, l='MpServer', x=172.44, y=61.81, z=-151.31], EntityBat['Bat'/601, l='MpServer', x=197.33, y=13.33, z=-177.79], EntityBat['Bat'/605, l='MpServer', x=182.42, y=16.08, z=-182.59], EntityBat['Bat'/625, l='MpServer', x=257.72, y=37.16, z=-198.56], EntityBat['Bat'/626, l='MpServer', x=259.25, y=35.03, z=-199.23], EntityBat['Bat'/627, l='MpServer', x=260.64, y=35.40, z=-197.42], EntitySkeleton['Skeleton'/681, l='MpServer', x=192.50, y=16.00, z=-188.50], EntityBat['Bat'/779, l='MpServer', x=213.06, y=14.76, z=-170.63], EntityCreeper['Creeper'/801, l='MpServer', x=240.25, y=21.00, z=-196.53], EntityCreeper['Creeper'/802, l='MpServer', x=239.34, y=21.00, z=-196.50], EntitySkeleton['Skeleton'/803, l='MpServer', x=233.50, y=22.00, z=-197.50], EntityBat['Bat'/835, l='MpServer', x=203.97, y=17.09, z=-139.16], EntityBat['Bat'/917, l='MpServer', x=202.88, y=37.10, z=-179.78], EntitySkeleton['Skeleton'/991, l='MpServer', x=290.47, y=16.00, z=-238.91], EntityCreeper['Creeper'/1066, l='MpServer', x=194.25, y=46.00, z=-174.88], EntityCreeper['Creeper'/1067, l='MpServer', x=190.13, y=46.00, z=-179.25], EntityCreeper['Creeper'/1068, l='MpServer', x=186.50, y=46.00, z=-179.50], EntitySpider['Spider'/1069, l='MpServer', x=200.28, y=41.09, z=-168.72], EntityZombie['Zombie'/1070, l='MpServer', x=197.00, y=38.00, z=-167.44], EntityZombie['Zombie'/1071, l='MpServer', x=187.88, y=46.00, z=-178.41], EntityZombie['Zombie'/1072, l='MpServer', x=202.50, y=46.00, z=-178.50], EntitySkeleton['Skeleton'/1113, l='MpServer', x=297.13, y=16.00, z=-87.50], EntitySkeleton['Skeleton'/1114, l='MpServer', x=282.88, y=15.00, z=-86.56], EntitySkeleton['Spined Skeleton'/1115, l='MpServer', x=291.50, y=17.00, z=-89.50], EntityZombie['Zombie'/1117, l='MpServer', x=224.50, y=14.00, z=-102.03], EntitySpider['Spider'/1118, l='MpServer', x=224.50, y=14.00, z=-104.00], EntityBat['Bat'/1136, l='MpServer', x=194.51, y=23.23, z=-126.93], EntityCreeper['Creeper'/1171, l='MpServer', x=198.50, y=23.00, z=-124.66], EntityZombie['Zombie'/1174, l='MpServer', x=218.28, y=22.00, z=-145.31], EntityZombie['Zombie'/1175, l='MpServer', x=217.50, y=20.00, z=-141.50], EntityZombie['Zombie'/1176, l='MpServer', x=218.50, y=20.00, z=-140.50], EntityZombie['Zombie'/1177, l='MpServer', x=218.50, y=20.00, z=-139.50], EntityCreeper['Creeper'/1178, l='MpServer', x=199.50, y=42.00, z=-175.50], EntityZombie['Zombie'/1179, l='MpServer', x=189.69, y=40.00, z=-168.53], EntityBat['Bat'/1322, l='MpServer', x=197.71, y=23.44, z=-141.54], EntityBat['Bat'/1330, l='MpServer', x=175.11, y=13.64, z=-195.81], EntityBat['Bat'/1331, l='MpServer', x=294.09, y=23.97, z=-106.25], EntitySpider['Spider'/1337, l='MpServer', x=215.50, y=25.00, z=-152.50], EntityZombie['Zombie'/1340, l='MpServer', x=219.50, y=25.00, z=-150.50], EntitySkeleton['Skeleton'/1355, l='MpServer', x=191.41, y=16.00, z=-189.09], EntityItem['item.item.seeds'/5473, l='MpServer', x=246.13, y=69.00, z=-119.28], EntityZombie['Zombie'/1390, l='MpServer', x=233.50, y=39.00, z=-179.50], EntityZombie['Zombie'/1417, l='MpServer', x=212.47, y=25.00, z=-144.94], EntitySkeleton['Skeleton'/1420, l='MpServer', x=215.50, y=25.00, z=-150.50], EntitySpider['Spider'/1466, l='MpServer', x=201.97, y=15.00, z=-164.50], EntityEnderman['Enderman'/1467, l='MpServer', x=200.00, y=15.00, z=-164.50], EntityZombie['Zombie'/1584, l='MpServer', x=197.34, y=47.00, z=-183.66], EntityCreeper['Creeper'/1659, l='MpServer', x=194.50, y=46.00, z=-178.50], EntityCreeper['Creeper'/1660, l='MpServer', x=191.91, y=46.00, z=-175.19], EntityCreeper['Creeper'/1661, l='MpServer', x=195.97, y=46.00, z=-176.56], EntityCreeper['Creeper'/1662, l='MpServer', x=193.50, y=46.00, z=-179.50], EntityCreeper['Creeper'/1667, l='MpServer', x=297.50, y=16.00, z=-88.50], EntityCreeper['Creeper'/1670, l='MpServer', x=297.50, y=16.00, z=-91.50], EntitySkeleton['Skeleton'/1671, l='MpServer', x=298.50, y=16.00, z=-93.50], EntitySkeleton['Skeleton'/1749, l='MpServer', x=214.63, y=36.00, z=-174.13], EntityBrainyZombie['Angry Zombie'/1769, l='MpServer', x=232.50, y=29.00, z=-187.50], EntityBrainyZombie['Angry Zombie'/1770, l='MpServer', x=233.50, y=29.00, z=-190.50], EntityBrainyZombie['Angry Zombie'/1771, l='MpServer', x=232.50, y=29.00, z=-189.50], EntityZombie['Zombie'/1782, l='MpServer', x=189.53, y=49.00, z=-174.13], EntityEnderman['Enderman'/1993, l='MpServer', x=217.50, y=20.00, z=-93.50], EntityCreeper['Creeper'/2006, l='MpServer', x=298.09, y=15.00, z=-237.78], EntityCreeper['Creeper'/2007, l='MpServer', x=293.50, y=15.00, z=-240.50], EntitySkeleton['Skeleton'/2008, l='MpServer', x=297.50, y=15.00, z=-234.50], EntitySkeleton['Skeleton'/2009, l='MpServer', x=300.50, y=15.00, z=-238.50], EntitySkeleton['Skeleton'/2010, l='MpServer', x=298.44, y=15.00, z=-233.91]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 725998176 bytes (692 MB) / 2251816960 bytes (2147 MB) up to 3102212096 bytes (2958 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3328m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1732 45 mods loaded, 45 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   Forge{11.15.1.1732} [Minecraft Forge] (forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   intangible{0.0.21} [Intangible] (intangible-1.8.9-0.0.21.jar) 
    UCHIJAAAA   JEI{2.25.6.140} [Just Enough Items] (jei_1.8.9-2.25.6.140.jar) 
    UCHIJAAAA   abyssalcraft{1.9.0-pre-3} [AbyssalCraft] (AbyssalCraft-1.8.9-1.9.0-pre-3.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   aura{unspecified} [Aura Cascade] (AuraCascade-1.8.8-v0.2.2a.jar) 
    UCHIJAAAA   bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
    UCHIJAAAA   BattleTowers{1.5.5} [Battle Towers] (BattleTowers-1.8.8.jar) 
    UCHIJAAAA   BBG{3.0.0} [BetterBedrockGen] (BBG-3.0.0.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-15} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-15.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-779cc76.jar) 
    UCHIJAAAA   buildingbrickscompatvanilla{1.8.9-1.3.1} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.3.1.jar) 
    UCHIJAAAA   buildingbricks{1.8.9-1.3.1} [Building Bricks] (BuildingBricks-1.8.9-1.3.1.jar) 
    UCHIJAAAA   C4Lib{1.0.0} [C4Lib] (C4Lib-1.8-1.0.0-universal.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.10} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.10.jar) 
    UCHIJAAAA   DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   graves{1.8.9-b35-universal} [Graves Mod] (graves-1.8.9-b35-universal.jar) 
    UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons] (JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources] (JustEnoughResources-1.8.9-0.3.1.jar) 
    UCHIJAAAA   launchgui{1.8.8-2.0.1-19} [LaunchGUI] (LaunchGui-1.8.8-2.0.1-19-client.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar) 
    UCHIJAAAA   packingtape{0.3.5} [Packing Tape] (Packing Tape-0.3.5.jar) 
    UCHIJAAAA   Psi{beta-12} [Psi] (Psi-beta-12.jar) 
    UCHIJAAAA   RandomThings{3.6.2} [Random Things] (RandomThings-MC1.8.9-3.6.2.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.0} [Storage Drawers] (StorageDrawers-1.8.9-2.4.0.jar) 
    UCHIJAAAA   thaumicbases{1.4.189.23} [Thaumic Bases] (ThaumicBases-2.1.189.23.jar) 
    UCHIJAAAA   thaumicinfusion{4.78} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.78.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
    UCHIJAAAA   yampst{1.3.6} [YAMPST] (Yampst-Simply Magic 2-0.0.1.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 560/PCIe/SSE2'
    [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore''Thaumic Infusion'
    Launched Version: forge-11.15.1.1732
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 560/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.82, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
```

**Comment by DrasticDemise** [comment]
Was this with every world you attempted to create or just this one time?

**Comment by Bluerobin427** [comment]
It's happened on at least the three worlds I just tried. It seems to crash when I look at a peony sitting on a half-block of grass, but it might be other flowers/plants too. I just noticed it with peonies in two of the three.

**Comment by DrasticDemise** [comment]
Disabled the mod, thanks for the report.
